export type Phone = {
  id: number;
  category: string;
  phoneId: string;
  itemId: string;
  name: string;
  fullPrice: number;
  price: number;
  screen: string;
  capacity: string;
  color: string;
  ram: string;
  year: number;
  image: string;
  imageUrl: string;
  count: number;
  priceDiscount: number;
  priceRegular: number;
  resolution: string;
  images: string[];
  colorsAvailable: string[];
  namespaceId: string;
  capacityAvailable: string[];
};
